site_name: Event Driven Toolkit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: yellow
      accent: amber

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/a-inacio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/antonio-manuel-inacio/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Constructs:
    - Creational:
      - action.md
      - event.md
      - injector.md
    - Behavioral:
      - actor.md
      - executor.md
      - delayable.md
      - director.md
      - eventhub.md
      - loopable.md
      - statemachine.md
    - Concurrency:
      - promise.md
      - expectable.md
      - expirable.md
  - Getting Started: getting-started.md
  - A Golang primer: a-golang-primer.md

copyright: |
  &copy; 2023 <a href="https://github.com/a-inacio"  target="_blank" rel="noopener">António Inácio</a>